config/routes.rb
Rails.application.routes.draw do
  resources :especimen

  resources :usuarios
  resources :usuario_sessions
  get 'login' => 'usuario_sessions#new', as: :login
  get 'logout' => 'usuario_sessions#destroy', as: :logout

  get 'welcome/index'

  root 'welcome#index'

end

app/models/especiman.rb
class Especiman < ActiveRecord::Base
	validates_presence_of :extension, :dominio, :filo, :clase, :orden, :familia, :genero, :especie
	FOTOS = File.join Rails.root, 'public', 'photo_store'
	after_save :guardar_foto

	
	def photo=(file_data)
		unless file_data.blank?
			@file_data = file_data
			self.extension = file_data.original_filename.split('.').last.downcase			
		end
	end

	def photo_filename
		File.join FOTOS, "#{id}.#{extension}"
	end
	def photo_path
		"/photo_store/#{id}.#{extension}"
	end
	def has_photo
		File.exists? photo_filename
	end
	private

	def guardar_foto
		if @file_data
			FileUtils.mkdir_p FOTOS
			File.open(photo_filename, 'wb') do |f|
				f.write(@file_data.read)
			end
			@file_data = nil	
		end	
	end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :especimen
  validates_presence_of :nameuser, :email
  validates_confirmation_of :password, message: "Ambos campos deven coincidir", if: :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/especimen_controller.rb
class EspecimenController < ApplicationController
  before_action :set_especiman, only: [:show, :edit, :update, :destroy]

  # GET /especimen
  # GET /especimen.json
  def index
    @especimen = Especiman.all
  end

  # GET /especimen/1
  # GET /especimen/1.json
  def show
  end

  # GET /especimen/new
  def new
    @especiman = Especiman.new
  end

  # GET /especimen/1/edit
  def edit
  end

  # POST /especimen
  # POST /especimen.json
  def create
    @especiman = Especiman.new(especiman_params)

    respond_to do |format|
      if @especiman.save
        format.html { redirect_to @especiman, notice: 'Especiman was successfully created.' }
        format.json { render :show, status: :created, location: @especiman }
      else
        format.html { render :new }
        format.json { render json: @especiman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especimen/1
  # PATCH/PUT /especimen/1.json
  def update
    respond_to do |format|
      if @especiman.update(especiman_params)
        format.html { redirect_to @especiman, notice: 'Especiman was successfully updated.' }
        format.json { render :show, status: :ok, location: @especiman }
      else
        format.html { render :edit }
        format.json { render json: @especiman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especimen/1
  # DELETE /especimen/1.json
  def destroy
    @especiman.destroy
    respond_to do |format|
      format.html { redirect_to especimen_url, notice: 'Especiman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especiman
      @especiman = Especiman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especiman_params
      params.require(:especiman).permit(:extension, :photo, :dominio, :filo, :clase, :orden, :familia, :genero, :especie, :observaciones)
    end
end

app/controllers/usuario_sessions_controller.rb
class UsuarioSessionsController < ApplicationController
	def new
		@usuario = Usuario.new
	end
	def create
		if @usuario= login(params[:email],params[:password])
			redirect_back_or_to(new_especiman_path, message: "Bienvenido")
		else
		flash.now[:alert] = "Especimen no encontrado"
		render action: 'new'
		end
	end
	def destroy
		logout
		redirect_to(new_usuario_path, message: "Adios")
		
	end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nameuser, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/especimen_helper.rb
module EspecimenHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/especimen/_form.html.erb
<%= form_for(@especiman, html: {multipart: true}) do |f| %>
  <% if @especiman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@especiman.errors.count, "error") %> prohibited this especiman from being saved:</h2>

      <ul>
      <% @especiman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
      <div class="page-header">
        <h1>InsecTem<small> Tus Imágenes!</small></h1>
      </div>
      <!-- Main hero unit for a primary marketing message or call to action -->
      

      <!-- inicio fila 1 -->
      <div class="row">
        <div class="span11">
          <br>
          <br>
          <br>
          <br>
          <br>
          <br>
          

          <img src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xfp1/t1.0-9/10477073_10203546679220025_797868925739391438_n.jpg" />
         <!--<img src="http://placehold.it/1200x400" />-->  
         <br>
         <br>
          <p>Ingresa los datos del artrópodo que encontraste juntos haremos que InsecTem sea cada día mas grande.
              Recuerda subir la información de forma correcta. ¡Muchas Gracias!</p>
          <br>
            <div class="actions">
            <button class="btn btn-inverse">Aceptar</button> <% f.submit %> 
          </div>
          </p> 
        </div>
        <div class="span3">
          <h2>Subir Imagen</h2>
          <div class="field">
            <%= f.file_field :photo %>
          </div>
          <div class="field">
            <%= f.text_field :dominio, :value => "Animal"  %>
          </div>
          <div class="field">
            <%= f.text_field :filo, :value => "Arthropoda" %>
          </div>
          <div class="field">
            <%= f.text_field :clase, :placeholder => 'Clase' %>
          </div>
          <div class="field">
            <%= f.text_field :orden, :placeholder => 'Orden' %>
          </div>
          <div class="field">
            <%= f.text_field :familia, :placeholder => 'Familia' %>
          </div>
          <div class="field">
            <%= f.text_field :genero, :placeholder => 'Genero' %>
          </div>
          <div class="field">
            <%= f.text_field :especie, :placeholder => 'Especie' %>
          </div>
          <div class="field">
            <%= f.text_area :observaciones, :placeholder => 'Observaciones' %>
          </div>
          
               

            </form>
        </div>
<% end %>

app/views/especimen/edit.html.erb
<h1>Editing especiman</h1>

<%= render 'form' %>

<%= link_to 'Show', @especiman %> |
<%= link_to 'Back', especimen_path %>

app/views/especimen/index.html.erb
<h1>Listing especimen</h1>

<table>
  <thead>
    <tr>
      <th>Genero</th>
      <th>Especie</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especimen.each do |especiman| %>
      <tr>
        
        <td><%= especiman.genero %></td>
        <td><%= especiman.especie %></td>
        <td><%= especiman.observaciones %></td>
        <td><%= link_to 'Show', especiman %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especiman', new_especiman_path %>

app/views/especimen/new.html.erb
<%= render 'form' %>

app/views/especimen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  
    <%= image_tag @especiman.photo_path %> 

</p>

<p>
  <strong>Reino:</strong>
  <%= @especiman.dominio %>
</p>

<p>
  <strong>Filo:</strong>
  <%= @especiman.filo %>
</p>

<p>
  <strong>Clase:</strong>
  <%= @especiman.clase %>
</p>

<p>
  <strong>Orden:</strong>
  <%= @especiman.orden %>
</p>

<p>
  <strong>Familia:</strong>
  <%= @especiman.familia %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @especiman.genero %>
</p>

<p>
  <strong>Especie:</strong>
  <%= @especiman.especie %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @especiman.observaciones %>
</p>

<%= link_to 'Edit', edit_especiman_path(@especiman) %> |
<%= link_to 'Back', especimen_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Insectem</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
   
   	<meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="">
      <meta name="author" content="">
      <link href="bootstrap.css" rel="stylesheet">
      <style type="text/css">
         body {
           padding-top: 50px;
           padding-bottom: 40px;
         }
      </style>
      <link href="bootstrap-responsive.css" rel="stylesheet">
      <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
      <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                      <link rel="shortcut icon" href="../assets/ico/favicon.png">
   
   </head>
   <body>
      <div class="navbar navbar-inverse navbar-fixed-top">
         <div class="navbar-inner">
               <div class="container">
                  
                  
               
               <div class="nav-collapse collapse">
                  <ul class="nav">
                    <li><p class="navbar-text navbar-left">InsecTem</p></li>
                        
                    <% if current_user  %>
                      <li ><%= link_to 'Nuevos Especimenes', new_especiman_path %></li>
                    <% else %>
                      <li><%= link_to 'Inicio', new_usuario_path %></a></li>
                      
                    <% end %>
                    <li><%= link_to 'Especiemenes', especimen_path %></li>
                  </ul>
                  <form class="navbar-form pull-right">
                     <% if current_user  %>
                          <button type="submit" class="btn"><%= link_to 'Logout', logout_path %></button>
                     <% else %>
                        <button type="submit" class="btn"> <%=link_to "Login", login_path %> </button> 
                     <% end %>
                  </form>

              </div>
                    </form>
               </div><!--/.nav-collapse -->
         </div>
      </div>
        <%= yield %>
   </body>
</html>

app/views/usuario_sessions/new.html.erb
<%= form_tag usuario_sessions_path, :method =>  :especimen do  %>

     <div class="container">
    <div class="hero-unit">
	  	<p class="text-center"><h1><big>Bienvenido!</big></h1><p>
        <h4>Ahora haces parte de los usuarios de InsecTem, puedes iniciar tu historial en este sitio subiendo todas las fotos de insectos que desees con la informacion correspondiente y ampliar tus conocimientos sobre la gran diversidad de insectos que habitan en nuestro planeta! Además puedes consultar, modificar y denunciar la información suministrada por otros usuarios</p>
        
    	<div class="container">
    	<div class = "field">
      		<%= label_tag :email %>  		<%= text_field_tag :email %>
      		<%= label_tag :password %>
      		<%= password_field_tag :password %>
      		</div>
      	<div class = "actions">
      		<button class="btn btn-inverse">Iniciar Insectem</button> <% submit_tag %>
      	</div>
      </div>

      	</div>
        </div>
    </div>
        


<% end %>

app/views/usuarios/_form.html.erb
<!DOCTYPE html>
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
      <div class="page-header">
        <h1>InsecTem <small> Bienvenido!</small></h1>
      </div>
      <!-- Main hero unit for a primary marketing message or call to action -->
      

      <!-- inicio fila 1 -->
      <div class="row">
        <div class="span8">
         <img src="https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xpf1/t1.0-9/10482856_10203531409718297_1700772593121760516_n.jpg" />
         <!--<img src="http://placehold.it/600x300" /> -->
          <h3>Información</h3>
          En este sitio, puedes indagar y solucionar todas tus dudas sobre los datos relacionados con los insectos que habitan en Colombia y el mundo.
            Todo esto lo puedes realizar desde cualquier lugar, prueba nuestra aplicación movil de Insectem</p>
          <a class="btn btn-inverse" href="#">Descargar aplicacion Movil</a></p>
        </div>
        <div class="span4">
          <!--<img src="http://placehold.it/300x150" />-->
          <h2>Registro</h2>
          <form>
            <legend>Ingresa tus datos</legend>
            <!--<label>Nombre</label>-->
            <div class="field">
              <%= f.text_field  :nameuser, :placeholder => 'Nombre de usuario'  %>
            </div>
            <div class="field">
              <%= f.text_field :email, :placeholder => 'Email' %>
            </div>
            <div class="field">
              <%= f.password_field :password, :placeholder => 'Contraseña'%>
            </div>
            <div class="field">
              <%= f.password_field :password_confirmation, :placeholder => 'Confirmar contraseña' %>
            </div>
            </form>
            <div class="actions">
              <button class="btn btn-inverse">Aceptar</button> <% f.submit %>
            </div>
        </div>
      </div>
  </div> <!-- /container -->

  

  
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nameuser</th>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nameuser %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.crypted_password %></td>
        <td><%= usuario.salt %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<%= render 'form' %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nameuser:</strong>
  <%= @usuario.nameuser %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @usuario.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @usuario.salt %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/welcome/index.html.erb
<div class="container">
	<div class="span11"><p class="text-center">Insectem<p></big></div>
	<img src="https://scontent-b-mia.xx.fbcdn.net/hphotos-xap1/t1.0-9/10492186_10203549385767687_434538568700010874_n.jpg">
</dic>